#!/bin/bash

# Copyright (c) 2026 harveyhans
#



# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Works with all sites supported by yt-dlp, 
# see https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md
# for more details.

# Check if URL was provided
if [ -z "$url" ]; then
    echo "Error: No URL provided"
    echo "Usage: $0 <url>"
    echo "Example: $0 \"https://www.youtube.com/watch?v=...\""
    exit 1
fi

# Also check if it's actually a URL (not "else" or other garbage)
if [[ "$url" != "http"* ]] && [[ "$url" != *"."* ]]; then
    echo "Error: '$url' doesn't look like a valid URL"
    exit 1
fi

url="$1"
filename="%(id)s"
if [[ "$url" == *"youtube.com"* || "$url" == *"youtu.be"* ]]; then
	filename="%(title)s_%(epoch)s"
	cookies_arg="--cookies $HOME/yt-dlp/.youtube.com_cookies.txt"
	youtube=1
fi

storage="$HOME/storage"

echo -e "\e[33mSource code: \e[4mhttps://github.com/kairusds/termux-url-opener"

OPT=$(termux-dialog radio -v "Download MP3,Download Video" -t "What do you want to do with $url?" | jq ".text" -r)

if [[ "$OPT" = "Download MP3" ]]; then
	yt-dlp \
		-f "best/bestaudio" \
		$cookies_arg \
		--ignore-errors \
		--no-mtime \
		--extract-audio \
		--audio-format mp3 \
		-o "$storage/music/%(uploader)s - %(title)s.%(ext)s" \
		--audio-quality 0 \
		"$url" \
		--download-archive $HOME/archive.txt \
		--embed-thumbnail \
		--convert-thumbnails webp \
		--add-metadata \
		--postprocessor-args 'EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf "crop=min(iw\,ih):min(iw\,ih)"' \
		--exec "termux-media-scan"
elif [[ "$OPT" = "Download Video" ]]; then
	yt-dlp \
		--no-mtime \
		-f "bestvideo+bestaudio/best" \
		$cookies_arg \
		--ignore-errors \
		-o "$storage/movies/Termux/$filename.%(ext)s" \
		--restrict-filenames \
		"$url" \
		-S "res,vcodec:h264,acodec:m4a,ext" \
		--merge-output-format "mp4/mkv" \
		--downloader $PREFIX/bin/aria2c \
		--downloader-args "-j 16 -s 16 -x 16 -k 1M" \
		--exec "termux-media-scan"
fi
